List<String> availaibleProfessionFr = [
  "Agent de joueur sportif",
  "Conseiller des activités physiques et sportives (APS)",
  "Directeur des sports d’une commune, des conseils régionaux ou départementaux",
  "Opérateur des APS",
  "Inspecteur de la jeunesse et des sports",
  "Manager des organisations sportives",
  "Organisateur d’évènements sportifs",
  "Pro gamer",
  "Organisateur e-Sport",
  "Juriste",
  "Avocat du sport",
  "Assureur pour les sportifs",
  "Kinésithérapeuthe sportif",
  "Sophrologue",
  "Ostéopathe",
  "Médecin du sport",
  "Diététicien du sport",
  "Préparateur physique",
  "Recherche équipement de sport",
  "Recherche en biologie du sport",
  "Moniteur de golf",
  "Commissaire de parcours",
  "Animateur de parcours",
  "Caddy master",
  "Directeur de golf",
  "Jardinier et intendant de terrain",
  "Attaché de presse auprès d’un sportif  ou d’une fédération ",
  "Agent de joueur",
  "Organisateur d’événements sportifs  ",
  "Chef de la publicité en externe ",
  "Journaliste sportif  ",
  "Directeur de la communication  pour une marque de sport ",
  "Responsable marketing pour une marque de sport ",
  "Moniteur de bateau-école      ",
  "Moniteur de voile ",
  "Chef de base nautique",
  "Directeur de centre nautique ",
  "Officier de port principal ",
  "Officier de port adjoint     ",
  "Skipper professionnel ",
  "Educateur sportif titulaire d’un BEES ",
  "Moniteur de ski alpin ou nordique",
  "Moniteur d’escalade ",
  "Moniteur de parachute de parapente ",
  "Animateur responsable d’animation ",
  "Educateur sportif ",
  "Entraîneur sportif ",
  "Animateur de centres de loisirs ",
  "Animateur socioculturel ",
  "Professeur d'EPS ",
  "Instituteur ",
  "Palefrenier ",
  "Les métiers de soigneur ",
  "Guide équestre ",
  "Garçon de cour ",
  "Cavalier d’entraînement (Interview)",
  "Animateur d'un centre équestre ",
  "Directeur  de centre équestre",
  "Arbitre",
  "Cascadeur",
  "Danseurs ",
  "Danseurs de ballet ",
  "Danseurs nus ",
  "Présentateur de spectacles ",
  "Artiste du cirque ",
  "Responsable de rayons pour un magasin de sport ",
  "Vendeur pour un magasin de sport ",
  "Directeur de la communication pour une marque de sport ",
  "Coordonnateur des ventes pour un magasin de sport ",
  "Directeur de magasin de sport ",
  "Vendeur Internet de séjours sportifs ",
  "Accompagnateur de voyage ",
  "Directeur d’établissement ou de centres de vacances",
  "Directeur d’un club ou association ",
  "Accompagnateur en moyenne montagne Guide de haute montagne ",
  "Maître nageur sauveteur  ",
  "Surveillant de baignade ",
  "Palefrenier ",
  "Accompagnateur de tourisme équestre  ",
  "Directeur d’un centre nautique ",
  "Inspecteur de la jeunesse, des sports et des loisirs  ",
  "Conseillers territoriaux des activités physiques et sportives ",
  "Educateurs territoriaux des activités physiques et sportives  ",
  "Responsable d’un gymnase public ",
  "Responsable d’une piscine publique ",
  "Directeur des sports d’une commune, des conseils régionaux ou départementaux",
  "Conseiller technique régional ",
  "Enseignant d’éducation physique et sportive ",
  "Professeur de sport ",
  "Professeur d’Université section STAPS ",
  "Directeur de formation à l’INSEP  ",
  "Entraîneur  pour une fédération, un club ou une association sportive ",
  "Conseiller technique régional ",
  "Pilote automobile",
  "Ingénieur en sport auto",
  "Mécanicien sport auto",
  "Commissaire sportif",
  "Commissaire technique",
  "Éducateur sportif ",
  "Educateur sportif des métiers de la forme",
  "Entraîneur sportif",
  "Sportif de haut niveau",
  "Moniteur de voile",
  "Professeur d’EPS",
  "Guide de haute montagne",
  "Moniteur de ski",
  "Maître-nageur sauveteur",
  "Moniteur de plongée",
  "Moniteur d’EPMS",
  "Enseignant en activité physique adaptée",
  "Professeur de sport",
  "Animateur/responsable d’animation",
  "Accompagnateur de tourisme équestre ",
  "Arbitre",
  "Kinésithérapeute du sport",
  "Médecin du sport",
  "Nutritionniste sportif",
  "Préparateur physique",
  "Directeur de salle de sport",
  "Chef de produit sportif ",
  "Responsable commercial sportif",
  "Responsable marketing sportif",
  "Responsable sponsoring",
  "Responsable hospitalité ",
  "Chef de projet événementiel sportif",
  "Journaliste sportif",
  "Responsable communication dans le sport",
  "Attaché de presse dans le sport",
  "Juriste du sport",
  "Directeur de magasin de sport",
  "Vendeur dans la grande distribution (sport)",
  "Skiman - Vendeur technicien ski",
  "Trader sportif",
  "Conseiller des activités physiques et sportives (APS)",
  "Opérateur des APS",
  "Inspecteur de la jeunesse et des sports",
  "Manager des organisations sportives",
  "Organisateur d’évènements sportifs",
  "Pro gamer",
  "Organisateur e-Sport",
  "Pisteur secouriste ",
  "Chef d'exploitation des remontées mécaniques ",
  "Conducteur de remontées mécaniques ",
  "Responsable d’une salle de sport ",
  "Garde-chasse ",
  "Pilote de drone",
  "Garde-pêche ",
  "Directeur des sports d’une commune, des conseils régionaux ou départementaux",
];
