List<String> availaibleSportFr = [
  "Boxe américaine (Full-contact)",
  "BMX",
  "BMX freestyle",
  "BMX Supercross",
  "Cyclisme en salle",
  "Cyclisme artistique",
  "Cycle-ball",
  "Cyclisme sur piste",
  "Cyclisme sur route",
  "Ultracyclisme",
  "Cyclo-cross",
  "Trial",
  "Vélo tout terrain",
  "Aïkido",
  "Bando et Banshay",
  "Capoeira",
  "Hapkido",
  "Ju-jitsu (jujutsu)",
  "Jiu-jitsu brésilien",
  "Judo",
  "Kalarippayatt",
  "Karaté",
  "Kendo",
  "Kobudo",
  "Krabi krabong",
  "Muay-boran",
  "Ninjutsu",
  "Sumo",
  "Taekwondo",
  "Tai-chi-chuan",
  "Unifight",
  "Viet vo dao",
  "Viet vu dao",
  "Wushu (Kung Fu)",
  "Boxe",
  "Boxe anglaise",
  "Boxe birmane (Lethwei)",
  "Boxe française (Savate)",
  "Boxe thaïlandaise",
  "Kick-boxing américain",
  "Kick-boxing japonais (K1)",
  "Canne et Bâton de combat",
  "Escrime",
  "Lutte",
  "Brancaille",
  "Catch",
  "Grappling",
  "Gouren (Lutte bretonne)",
  "Lutte gréco-romaine",
  "Lutte libre",
  "Lutte sénégalaise",
  "Lutte mongole",
  "Lutte turque",
  "Naban (Lutte birmane)",
  "Ssirum",
  "Sambo",
  "Mixed martial art (MMA)",
  "Krav-maga",
  "Sport chanbara",
  "Sports de glace",
  "Bandy",
  "Bobsleigh",
  "Curling",
  "Eisstock",
  "Hockey sur glace",
  "Luge",
  "Patinage",
  "Patinage artistique",
  "Danse sur glace",
  "Patinage synchronisé",
  "Patinage de vitesse",
  "Short-track",
  "Ringuette",
  "Skeleton",
  "Sports de plein air et de nature",
  "Alpinisme",
  "Canyonisme",
  "Course d'orientation",
  "Descente en rappel",
  "Escalade sportive",
  "Bloc (escalade)",
  "Grimpe d'arbres",
  "Pêche sportive",
  "Escalade glaciaire",
  "Raid nature",
  "Randonnée pédestre",
  "Spéléologie",
  "Ultra-trail",
  "Sports aériens",
  "Aéromodélisme",
  "Aérostation",
  "Base jump",
  "Cerf-volant",
  "Deltaplane",
  "Parachutisme",
  "Parapente",
  "ULM",
  "Vol libre",
  "Vol à voile",
  "Voltige aérienne",
  "Épreuves combinées",
  "Triathlon",
  "Duathlon",
  "Aquathlon",
  "Aquabike",
  "Cross triathlon",
  "Triathlon d'hiver",
  "Pentathlon moderne",
  "Combiné nordique",
  "Biathlon",
  "Racketlon",
  "Micronesian all around",
  "Sports de précision",
  "Airsoft",
  "Ball-trap",
  "Billards",
  "Billard français",
  "Billard américain",
  "Billard anglais",
  "Snooker",
  "Boule bretonne",
  "Boulingrin",
  "Boomerang",
  "Bowling",
  "Croquet",
  "Fléchettes",
  "Golf",
  "Jukskei",
  "Minigolf",
  "Paintball",
  "Jeux de palets",
  "Pétanque",
  "Boule de fort",
  "Quilles de neuf",
  "Sarbacana",
  "Sport boule (boule lyonnaise)",
  "Tir",
  "Tir à l'arc",
  "Sports nautiques",
  "Apnée",
  "Aviron",
  "Aviron de mer",
  "Aviron Indoor",
  "Barque de Sauvetage",
  "Bateau-dragon",
  "Canoë-kayak",
  "Char à voile",
  "Chasse sous-marine",
  "Dragon Boat",
  "Hockey subaquatique",
  "Motomarine",
  "Joutes nautiques",
  "Kayak-polo",
  "Kitesurf",
  "Nage avec palmes",
  "Nage en eau libre",
  "Nage en eau vive",
  "Motonautisme",
  "Natation",
  "Natation synchronisée",
  "Planche à voile",
  "Plongée sous-marine",
  "Plongeon",
  "Rafting",
  "Rugby subaquatique",
  "Ski nautique",
  "Surf",
  "Voile",
  "Water polo",
  "Wakeboard",
  "Wakesurf",
  "Sports de glisse",
  "Ski",
  "Saut à ski",
  "Snowboard",
  "Ski alpin",
  "Ski de randonnée",
  "Ski acrobatique",
  "Ski freestyle",
  "Ski freeride",
  "Ski de fond",
  "Ski de vitesse",
  "Ski extrême",
  "Ski télémark",
  "Sport électronique",
  "Bodyboard",
  "Freeboard",
  "Kayak Surf",
  "Kiteski",
  "Kitesnow",
  "Mountainboard",
  "Roller",
  "Skateboard",
  "Speed-riding",
  "Streetboard",
  "Voile sur glace",
  "Longskate",
  "Trottinette Freestyle",
  "Belote",
  "Bridge",
  "Dames",
  "Échecs",
  "Go",
  "Poker",
  "Scrabble (marque déposée)",
  "Échecs chinois",
  "Speedcubing",
  "Footbag",
  "Main à main",
  "Marche nordique",
  "Sport stacking",
  "Tricking",
];
